exp_id: D15
data:
  file_name: 
    /workspaces/codex-analysis/data/FallopianTube/D15/img0011/img0011.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/FallopianTube/D15/img0011/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/FallopianTube/D15/img0011/processed_hubmap/hubmap_annotations
