# Top-level configuration for CODEX pipeline
exp_id: D18_Scan1_1
# -----------------------------------------------------------------------------
# (A) Data Source and Basic Image Settings
# -----------------------------------------------------------------------------
data:
  # Path to the main .qptiff or .tiff file for the CODEX image
  file_name: FallopianTube/D18/Scan1/D18_Scan1_tissue_1.ome.tiff

  # Path to the TSV file containing antibody definitions (one row per channel)
  antibodies_file: FallopianTube/D18/Scan1/extras/antibodies.tsv

  # Microns per pixel for this image; used in downstream calculations (e.g., segmentation scaling)
  image_mpp: 0.5

  # Whether to compute and save channel-level statistics (min, max, 95th percentile, etc.)
  generate_channel_stats: true

# -----------------------------------------------------------------------------
# (B) Channel Configuration
# -----------------------------------------------------------------------------
channels:
  # Name of the nuclear marker channel (must match an entry in the antibodies file)
  nuclear_channel: DAPI

  # Name(s) of the whole-cell marker channel(s). If multiple, they will be merged.
  wholecell_channel:
    - Pan-Cytokeratin
    - Collagen IV
    - FUT4
patching:
  # Size (height, width) of each patch (in pixels)
  patch_height: 1000
  patch_width: 1000

  # Overlap fraction between adjacent patches (0.1 means 10% overlap)
  overlap: 0.1

# -----------------------------------------------------------------------------
# (D) Visualization Settings
# -----------------------------------------------------------------------------
visualization:
  # Whether to save an RGB visualization of the entire sample (e.g., nuclear vs. whole-cell)
  visualize_whole_sample: true

  # How to downsample the visualization image (null = no downsampling, -1 = auto-downsampling, 
  # or positive integer for specific downsample factor)
  downsample_factor: -1.0

  # Whether to apply contrast enhancement to the visualization (slower but better quality)
  enhance_contrast: true

  # Whether to save RGB visualizations of all patches
  visualize_patches: false

  # Whether to save the raw multi-channel patches to disk
  save_all_channel_patches: false

  # Whether to visualize and save the segmentation mask overlay (after segmentation)
  visualize_segmentation: false

# -----------------------------------------------------------------------------
# (E) QC (Patch-Level Quality Control)
# -----------------------------------------------------------------------------
patch_qc:
  # Minimum fraction of non-zero pixels required for a patch to be considered valid
  non_zero_perc_threshold: 0.05

  # Minimum mean intensity for the patch to be considered informative
  mean_intensity_threshold: 1.0

  # Minimum standard deviation required to avoid marking patches as too "flat"
  std_intensity_threshold: 1.0

# -----------------------------------------------------------------------------
# (F) Segmentation Parameters and Output Options
# -----------------------------------------------------------------------------
segmentation:
  # Path to the segmentation model directory (e.g., for DeepCell or another tool)
  model_path: /workspaces/codex-analysis/data/deepcell/MultiplexSegmentation

  # If True, save segmentation masks as images
  save_segmentation_images: true

  # If True, pickle the entire codex_patches object (containing segmentation results, etc.)
  save_segmentation_pickle: true

# -----------------------------------------------------------------------------
# (G) Testing Data Disruption (Optional) 
#     If you do not want to disrupt your data, set "type" to null or remove this block.
# -----------------------------------------------------------------------------
testing:
  data_disruption:
    # Disruption type can be "downsampling" or "gaussian"
    type: NULL

    # Intensity level of disruption (1-5, for instance)
    level: -1.0

    # Whether to save the disrupted patches to disk (for debugging/testing)
    save_disrupted_patches: false

# -----------------------------------------------------------------------------
# (H) Evaluation Metrics
# -----------------------------------------------------------------------------
evaluation:
  compute_metrics: false

# -----------------------------------------------------------------------------
# (I) Parallel Processing Settings
# -----------------------------------------------------------------------------
parallel_processing:
  # Number of worker processes to use for parallelizable operations
  # Based on your system with 128 cores, use 4 workers as requested
  workers: 10
  
  # Maximum memory per worker in GB (0 = no limit)
  max_memory_per_worker: 0
  