data:
  file_name: 'FallopianTube/InHouse_conjugations/Donor_19_FT_4_slices/Slide_3/19-26_FT_Scan1_tissue_0.tiff'
  antibodies_file: 'FallopianTube/InHouse_conjugations/Donor_19_FT_4_slices/Slide_3/extra/antibody.tsv'
  image_mpp: 0.5  # Microns per pixel for the image during segmentation
  generate_channel_stats: True

channels:
  nuclear_channel: 'DAPI'
  wholecell_channel: ['Pan-Cytokeratin', 'Collagen IV']

patching:
  patch_height: 4000
  patch_width: 4000
  overlap: 0

visualization:
  visualize_whole_sample: True
  visualize_patches: True
  save_all_channel_patches: False

qc:
  non_zero_perc_threshold: 0.05  # Percentage of non-zero pixels to pass the filter
  mean_intensity_threshold: 1    # Minimum mean intensity to consider a patch as informative
  std_intensity_threshold: 1     # Minimum standard deviation to avoid marking noisy patches

segmentation:
  model_path: '/workspaces/codex-analysis/data/deepcell/MultiplexSegmentation'
  save_segmentation_results: True
