#!/bin/bash
# nohup bash /workspaces/codex-analysis/0-phenocycler-penntmc-pipeline/run_analysis_ft.sh > out/run_analysis_ft_$(date +%Y%m%d_%H%M%S).log 2>&1 &
# [1] Set experiment set name (matches exps/configs/analysis/<EXP_SET_NAME>)
EXP_SET_NAME="analysis_FHPR_PRE"

# [2] Define the base directory (adjust as needed)
ROOT_DIR="/workspaces/codex-analysis/0-phenocycler-penntmc-pipeline"

# [3] Define the path to the inner script that launches run_analysis.py
RUN_FILE="${ROOT_DIR}/scripts/run_analysis.sh"

# [4] Define input data directory (root generated by the main pipeline)
DATA_DIR="${ROOT_DIR}/out/main/main_FHPR_PRE"


# [5] Directory where your config files for analysis live
#     Example: each experiment has its own subfolder with an analysis config.
CONFIG_DIR="${ROOT_DIR}/exps/configs/analysis/${EXP_SET_NAME}"

# [6] Define the output and log directories for analysis
LOG_DIR="${ROOT_DIR}/logs/analysis/${EXP_SET_NAME}"
OUT_DIR="${ROOT_DIR}/out/analysis/${EXP_SET_NAME}"

# [7] Create them if they don't exist
mkdir -p "${OUT_DIR}"
mkdir -p "${LOG_DIR}"

# [8] Define an array of experiment identifiers (config + data must exist)
declare -a EXPERIMENTS=(
  "FHPR_PRE_scan1_1"
  "FHPR_PRE_scan1_2"
  "FHPR_PRE_scan1_3"  
  # Add additional experiment IDs as needed
)

# [9] Loop over experiments
for EXP_ID in "${EXPERIMENTS[@]}"; do
  ANALYSIS_CONFIG="${CONFIG_DIR}/${EXP_ID}/config.yaml"
  EXP_DATA_DIR="${DATA_DIR}/${EXP_ID}"
  if [ ! -f "${ANALYSIS_CONFIG}" ]; then
    echo "[WARN] Skipping ${EXP_ID}: missing config ${ANALYSIS_CONFIG}" >&2
    continue
  fi
  if [ ! -d "${EXP_DATA_DIR}" ]; then
    echo "[WARN] Skipping ${EXP_ID}: missing data directory ${EXP_DATA_DIR}" >&2
    continue
  fi
  # Create a log file for each experiment
  LOG_FILE="${LOG_DIR}/${EXP_ID}.log"
  echo "Initiating analysis for $EXP_ID"
  {
    echo "Current time: $(date)"
    echo "Running analysis for $EXP_ID"
    time bash "${RUN_FILE}" "$EXP_SET_NAME" "$EXP_ID" "$ROOT_DIR" "$DATA_DIR" "$CONFIG_DIR" "$OUT_DIR"
    echo "Experiment $EXP_ID analysis completed."
  } > "$LOG_FILE" 2>&1
done

echo "All analysis experiments completed."
