# /workspaces/codex-analysis/0-phenocycler-penntmc-pipeline/exps/configs/analysis/my_experiment/analysis_config.yaml
exp_id: D18_Scan1_2

analysis:
  # Directory containing the CSV or expression files for this analysis
  data_dir: test0206_main/D18_Scan1_2

  # Which patch index to analyze (if you have multiple patches)
  patch_index: 0

  # Whether to skip all plotting steps (for faster processing)
  skip_viz: false

  # Resolution parameter used by Leiden clustering
  clustering_resolution: 0.2

  norm_method: rank_fraction