exp_id: D342-RLL-18A6-11
data:
  file_name: URMC/D342-RLL-18A6-11/D342-RLL-18A6-11_Scan1.qptiff
  # antibodies_file: 'FallopianTube/D18/Scan1/extra/antibody.tsv'

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: 1
  downscale_factor: 64
  min_area: 500
  visualize: true
evaluation:
  compute_metrics: null
