exp_id: lung_d231
data:
  file_name: lung/D231/D231-RLL-11B3-3_Scan1.er.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: 1
  downscale_factor: 64
  min_area: 500
  visualize: true
