exp_id: D11
data:
  file_name: 
    /workspaces/codex-analysis/data/FallopianTube/D11/img0005/img0005.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: 4
  downscale_factor: 64
  min_area: 500
  visualize: true
  manual_mask_json: 
    /workspaces/codex-analysis/data/FallopianTube/D11/img0005/img0005_annotations.json
