# /workspaces/codex-analysis/0-phenocycler-penntmc-pipeline/exps/configs/analysis/my_experiment/analysis_config.yaml
exp_id: D18_Scan1_0

analysis:
  # Directory containing the CSV or expression files for this analysis
  data_dir: "/workspaces/codex-analysis/0-phenocycler-penntmc-pipeline/out/test-ft/exp-1"

  # Which patch index to analyze (if you have multiple patches)
  patch_index: 0

  # Whether to skip all plotting steps (for faster processing)
  skip_viz: false

  # Directory to store output results (figures, logs, final AnnData, etc.)
  output_dir: "/workspaces/codex-analysis/0-phenocycler-penntmc-pipeline/out/analysis/test_analysis/exp-1"

  # Resolution parameter used by Leiden clustering
  clustering_resolution: 0.35

  norm_method: "rank_fraction"