exp_id: D11_13
data:
  file_name: 
    /workspaces/codex-analysis/data/Ovary/D11_13_Scan1/D11_13_Scan1.er.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: 4
  downscale_factor: 64
  min_area: 500
  visualize: true
  manual_mask_json: 
    /workspaces/codex-analysis/data/Ovary/D11_13_Scan1/D11_13_Scan1_Oocytes.geojson
