exp_id: D231-RLL-11B3-4
data:
  file_name: URMC/D231-RLL-11B3-4/D231-RLL-11B3-4_Scan1.er.qptiff
  # antibodies_file: 'FallopianTube/D18/Scan1/extra/antibody.tsv'

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  skip_roi_crop: true
  n_tissue: 1
  downscale_factor: 64
  min_area: 500
  visualize: true
evaluation:
  compute_metrics: null
